<?php

namespace LV\LocationBundle\Repository;

/**
 * CSRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CSRRepository extends \Doctrine\ORM\EntityRepository
{
}
