<?php

namespace LV\LocationBundle\Repository;

/**
 * DisponibliliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibliliteRepository extends \Doctrine\ORM\EntityRepository
{
}
