<?php

namespace LV\LocationBundle\Repository;

/**
 * PaiementSoustraitanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementSoustraitanceRepository extends \Doctrine\ORM\EntityRepository
{
}
