<?php

namespace LV\LocationBundle\Repository;

/**
 * PaiementEcheanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementEcheanceRepository extends \Doctrine\ORM\EntityRepository
{
}
